Repository ssafy-mate/ssafy-mate_front-end, pull requests merged in 2022-03, with the labels that each got.

#94 Merge : 메인 홈 페이지 웹 최적화
  public/images/home/autonomy-project_link-img_large.png
  public/images/home/autonomy-project_link-img_medium.png
  public/images/home/autonomy-project_link-img_small.png
  public/images/home/common-project_link-img_large.png
  public/images/home/common-project_link-img_medium.png
  public/images/home/common-project_link-img_small.png
  public/images/home/mobile-chatting-sample-img_medium.png
  public/images/home/mobile-chatting-sample-img_small.png
  public/images/home/mobile-chatting-sample.png
  public/images/home/mobile-team-info-sample.png
  public/images/home/mobile-team-list-sample-img_medium.png
  public/images/home/mobile-team-list-sample-img_small.png
  public/images/home/mobile-team-list-sample.png
  public/images/home/pc-team-info-sample-img.png
  public/images/home/pc-team-info-sample.png
  public/images/home/pc-team-list-sample-img.png
  public/images/home/pc-team-list-sample.png
  public/images/home/pc-user-info-sample-img.png
  public/images/home/pc-user-info-sample.png
  public/images/home/pc-user-list-sample-img.png
  public/images/home/pc-user-list-sample.png
  public/images/home/specialization-project_link-img_large.png
  public/images/home/specialization-project_link-img_medium.png
  public/images/home/specialization-project_link-img_small.png
  public/images/projects/autonomy-project.gif
  public/images/projects/autonomy-project_link.png
  public/images/projects/common-project_link.png
  public/images/projects/specialization-project_link.png
  public/index.html
  public/videos/home/autonomy-project_animation.mp4
  public/videos/home/common-project_animation.mp4
  public/videos/home/specialization-project_animation.mp4
  src/components/common/Loading.tsx
  src/components/common/MenuBar.tsx
  src/components/common/ProfileTechStackTagWithLevel.tsx
  src/components/common/TechStackTag.tsx
  src/components/common/TechStackTagWithLevel.tsx
  src/components/home/HomeBannerCard.tsx
  src/components/home/HomeBannerSection.tsx
  src/components/home/IntroContainer.tsx
  src/components/home/IntroSection.tsx
  src/components/home/MobileServiceIntroSection.tsx
  src/components/home/PcBox.tsx
  src/components/home/ProjectLinkCard.tsx
  src/components/home/ProjectsSection.tsx
  src/components/projects/Pagenation.tsx
  src/components/user/UserTechStackTag.tsx
  src/styles/commonStyles.ts
  src/types/commonTypes.ts
Labels: Refactor

#95 Merge : 페이지 헤딩 처리 수정
  README.md
  readme_assets/home-page-headingsmap.png
  readme_assets/team-info-page-headingsmap.png
  readme_assets/team-list-page-headingsmap.png
  readme_assets/user-info-page-headingsmap.png
  src/components/home/ProjectLinkCard.tsx
  src/components/projects/RequestItem.tsx
  src/components/projects/TeamItem.tsx
  src/components/team/TeamMemberItem.tsx
  src/components/user/UserInfoSection.tsx
Labels: Fix, Refactor

#99 Merge : Document Title 수정 작업을 훅으로 모듈화, hooks 디렉터리 분리
  .env
  public/index.html
  src/components/account/BasicInformationSection.tsx
  src/components/account/ProfileInformationSection.tsx
  src/components/chatting/ChattingForm.tsx
  src/components/common/Header.tsx
  src/components/home/ProjectLinkCard.tsx
  src/components/policy/PrivacySection.tsx
  src/components/policy/TermsOfServiceSection.tsx
  src/components/projects/ProjectNavigation.tsx
  src/components/projects/ReceiveRequestListSection.tsx
  src/components/projects/RequestItem.tsx
  src/components/projects/SendRequestListSection.tsx
  src/components/projects/UserItem.tsx
  src/components/team/TeamCreateForm.tsx
  src/components/team/TeamEditForm.tsx
  src/components/team/TeamInfoSection.tsx
  src/components/user/UserInfoSection.tsx
  src/components/user/UserLabel.tsx
  src/hooks/reactQueryHooks/useReceiveRequests.ts
  src/hooks/reactQueryHooks/useSendRequests.ts
  src/hooks/reactQueryHooks/useTeamInfo.ts
  src/hooks/reactQueryHooks/useTeamList.ts
  src/hooks/reactQueryHooks/useUserInfo.ts
  src/hooks/reactQueryHooks/useUserList.ts
  src/hooks/reduxHooks/useMyTeamTechStacks.ts
  src/hooks/reduxHooks/useProfileInfo.ts
  src/hooks/reduxHooks/useProfileTeckStacks.ts
  src/hooks/reduxHooks/useProjectTrack.ts
  src/hooks/reduxHooks/useToken.ts
  src/hooks/reduxHooks/useUserId.ts
  src/hooks/reduxHooks/useUserIdName.ts
  src/hooks/reduxHooks/useUserProjectInfo.ts
  src/hooks/useDocumentTitle.ts
  src/hooks/useMyTeamId.ts
  src/hooks/useMyTeamInfo.ts
  src/hooks/useQueryString.ts
  src/hooks/useTextArea.ts
  src/pages/ChattingPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/HomePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/policy/PrivacyPage.tsx
  src/pages/policy/TermsOfServicePage.tsx
  src/pages/projects/SpecializationProjectReceiveRequestListPage.tsx
  src/pages/projects/SpecializationProjectSendRequestListPage.tsx
  src/pages/projects/SpecializationProjectTeamListPage.tsx
  src/pages/projects/SpecializationProjectUserListPage.tsx
  src/pages/projects/TeamCreatePage.tsx
  src/pages/teams/TeamEditPage.tsx
  src/pages/teams/TeamInfoPage.tsx
  src/pages/users/AccountEditPage.tsx
  src/pages/users/FindUserIdPage.tsx
  src/pages/users/NewPasswordPage.tsx
  src/pages/users/UserInfoPage.tsx
Labels: Refactor, Modify

#101 Merge : 코드 리팩터링
  public/images/assets/basic-profile-img.png
  public/images/assets/basic-team-logo.png
  public/images/assets/toggle-black.png
  public/images/common/default-profile-img.png
  public/images/common/default-team-logo.png
  public/images/common/ssafy-mate_logo.png
  public/images/common/ssafy-mate_logo_medium.png
  public/images/common/ssafy-mate_logo_small.png
  public/images/common/toggle-black.png
  public/images/projects/ai-video_animation.gif
  public/images/projects/ai-voice_animation.gif
  public/images/projects/blockchain-digital-money_animation.gif
  public/images/projects/blockchain-p2p_animation.gif
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/videos/projects/ai-video_animation.mp4
  public/videos/projects/ai-voice_animation.mp4
  public/videos/projects/bigdata-dispersion_animation.mp4
  public/videos/projects/bigdata-recommendation_animation.mp4
  public/videos/projects/blockchain-digital-money_animation.mp4
  public/videos/projects/blockchain-p2p_animation.mp4
  public/videos/projects/iot_animation.mp4
  src/components/account/BasicInformationSection.tsx
  src/components/account/FindUserIdCard.tsx
  src/components/account/ProfileInformationSection.tsx
  src/components/chatting/ChatRoomItem.tsx
  src/components/chatting/ChattingForm.tsx
  src/components/common/Header.tsx
  src/components/error/ErrorHeader.tsx
  src/components/projects/ProjectBannerCard.tsx
  src/components/projects/ProjectBannerSection.tsx
  src/components/projects/RequestItem.tsx
  src/components/projects/TeamItem.tsx
  src/components/projects/TeamListSearchForm.tsx
  src/components/projects/TeamRecruitmentSection.tsx
  src/components/projects/UserItem.tsx
  src/components/projects/UserListSearchForm.tsx
  src/components/projects/UserRecruitmentSection.tsx
  src/components/projects/skeletonUI/SkeletonTeamRecruitmentSection.tsx
  src/components/projects/skeletonUI/SkeletonUserRecruitmentSection.tsx
  src/components/signUp/AuthForm.tsx
  src/components/signUp/ProfileForm.tsx
  src/components/team/TeamCreateForm.tsx
  src/components/team/TeamEditForm.tsx
  src/components/team/TeamInfoSection.tsx
  src/components/team/TeamMemberItem.tsx
  src/components/user/UserInfoSection.tsx
  src/components/user/skeletonUI/SkeletonUserInfoSection.tsx
  src/mocks/database/team.ts
  src/types/commonTypes.ts
  src/utils/axios.ts
Labels: Refactor

#100 Delete : 패턴에 맞지 않는 컨테이너 컴포넌트 삭제
  src/components/signIn/SignInCard.tsx
  src/containers/SignInContainer.tsx
  src/pages/SignInPage.tsx
Labels: Modify

#105 Merge : 페이지 헤딩 처리 개편
  README.md
  readme_assets/home-page-headingsmap.png
  readme_assets/team-info-page-headingsmap.png
  readme_assets/team-list-page-headingsmap.png
  readme_assets/user-info-page-headingsmap.png
  src/components/common/Footer.tsx
  src/components/common/VisuallyHiddenHead.tsx
  src/components/home/HomeBannerCard.tsx
  src/components/home/HomeBannerSection.tsx
  src/components/home/IntroContainer.tsx
  src/components/home/IntroSection.tsx
  src/components/home/MobileServiceIntroSection.tsx
  src/components/home/ProjectLinkCard.tsx
  src/components/home/ProjectsSection.tsx
  src/components/projects/ProjectBannerCard.tsx
  src/components/projects/ProjectBannerSection.tsx
  src/components/projects/TeamItem.tsx
  src/components/projects/TeamRecruitmentSection.tsx
  src/components/projects/UserItem.tsx
  src/components/projects/UserRecruitmentSection.tsx
  src/pages/HomePage.tsx
  src/pages/projects/SpecializationProjectSendRequestListPage.tsx
  src/pages/projects/SpecializationProjectTeamListPage.tsx
  src/pages/projects/SpecializationProjectUserListPage.tsx
Labels: Refactor

#108 Merge : ReactQuery 변환 및 컴포넌트 리팩터링
  package.json
  src/App.tsx
  src/components/chatting/ChatMessageBox.tsx
  src/components/chatting/ChatMessageSection.tsx
  src/components/chatting/ChatProfileHeaderbar.tsx
  src/components/chatting/ChatRoomItem.tsx
  src/components/chatting/ChatRoomListSidebar.tsx
  src/components/chatting/ChatSection.tsx
  src/components/chatting/ChattingForm.tsx
  src/hooks/reactQueryHooks/useChatLog.ts
  src/hooks/reactQueryHooks/useChatRoomList.ts
  src/hooks/reactQueryHooks/useSendChat.ts
  src/index.tsx
  src/mocks/database/chatting.ts
  src/mocks/handlers/chattingHandlers.ts
  src/pages/ChatPage.tsx
  src/services/ChatService.ts
  src/utils/fetcher.ts
  yarn.lock
Labels: Refactor, Modify

#113 Merge : 다이얼에 지연 로딩(Lazy Loading) 적용 및 컴포넌트 디렉터리 구조 개편
  src/App.tsx
  src/components/home/common/ToTopButton.tsx
  src/components/home/homeBanner/HomeBannerCard.tsx
  src/components/home/homeBanner/HomeBannerContainer.tsx
  src/components/home/projectLinks/ProjectLinkCard.tsx
  src/components/home/projectLinks/ProjectLinksContainer.tsx
  src/components/home/projectLinks/ProjectTrackDialog.tsx
  src/components/home/serviceIntro/IntroSection.tsx
  src/components/home/serviceIntro/MobileServiceIntroSection.tsx
  src/components/home/serviceIntro/PcBox.tsx
  src/components/home/serviceIntro/ServiceIntroContainer.tsx
  src/components/projects/navigation/ProjectPageNavigation.tsx
  src/components/projects/projectTrackBanner/ProjectTrackBannerSection.tsx
  src/components/projects/projectTrackBanner/ProjectTrackCard.tsx
  src/components/projects/recruitment/EmptyBox.tsx
  src/components/projects/recruitment/Pagenation.tsx
  src/components/projects/recruitment/RecruitStatusBadge.tsx
  src/components/projects/recruitment/RecruitStatusTag.tsx
  src/components/projects/recruitment/TeamItem.tsx
  src/components/projects/recruitment/TeamRecruitmentSection.tsx
  src/components/projects/recruitment/UserItem.tsx
  src/components/projects/recruitment/UserRecruitmentSection.tsx
  src/components/projects/requestList/EmptyRequestBox.tsx
  src/components/projects/requestList/ReceiveRequestListSection.tsx
  src/components/projects/requestList/RequestItem.tsx
  src/components/projects/requestList/SendRequestListSection.tsx
  src/components/projects/searchForm/SearchFormWithTeams.tsx
  src/components/projects/searchForm/SearchFormWithUsers.tsx
  src/components/team/TeamInfoSection.tsx
  src/components/team/TeamMembersStatus.tsx
  src/components/user/UserInfoSection.tsx
  src/pages/HomePage.tsx
  src/pages/projects/SpecializedProjectReceiveRequestListPage.tsx
  src/pages/projects/SpecializedProjectSendRequestListPage.tsx
  src/pages/projects/SpecializedProjectTeamListPage.tsx
  src/pages/projects/SpecializedProjectUserListPage.tsx
  src/pages/projects/TeamCreatePage.tsx
  src/pages/teams/TeamEditPage.tsx
  src/pages/teams/TeamInfoPage.tsx
  src/pages/users/UserInfoPage.tsx
  src/types/commonTypes.ts
Labels: Refactor

#114 Merge : 서비스 버전 1.2.7 업데이트
  README.md
  package.json
  readme_assets/after-web-optimization.png
  readme_assets/user-info-page-headingsmap.png
  src/App.tsx
  src/components/home/common/ToTopButton.tsx
  src/components/home/homeBanner/HomeBannerCard.tsx
  src/components/home/homeBanner/HomeBannerContainer.tsx
  src/components/home/projectLinks/ProjectLinkCard.tsx
  src/components/home/projectLinks/ProjectLinksContainer.tsx
  src/components/home/projectLinks/ProjectTrackDialog.tsx
  src/components/home/serviceIntro/IntroSection.tsx
  src/components/home/serviceIntro/MobileServiceIntroSection.tsx
  src/components/home/serviceIntro/PcBox.tsx
  src/components/home/serviceIntro/ServiceIntroContainer.tsx
  src/components/projects/navigation/ProjectPageNavigation.tsx
  src/components/projects/projectTrackBanner/ProjectTrackBannerSection.tsx
  src/components/projects/projectTrackBanner/ProjectTrackCard.tsx
  src/components/projects/recruitment/EmptyBox.tsx
  src/components/projects/recruitment/Pagenation.tsx
  src/components/projects/recruitment/RecruitStatusBadge.tsx
  src/components/projects/recruitment/RecruitStatusTag.tsx
  src/components/projects/recruitment/TeamItem.tsx
  src/components/projects/recruitment/TeamRecruitmentSection.tsx
  src/components/projects/recruitment/UserItem.tsx
  src/components/projects/recruitment/UserRecruitmentSection.tsx
  src/components/projects/requestList/EmptyRequestBox.tsx
  src/components/projects/requestList/ReceiveRequestListSection.tsx
  src/components/projects/requestList/RequestItem.tsx
  src/components/projects/requestList/SendRequestListSection.tsx
  src/components/projects/searchForm/SearchFormWithTeams.tsx
  src/components/projects/searchForm/SearchFormWithUsers.tsx
  src/components/team/TeamInfoSection.tsx
  src/components/team/TeamMembersStatus.tsx
  src/components/user/UserInfoSection.tsx
  src/pages/HomePage.tsx
  src/pages/projects/SpecializedProjectReceiveRequestListPage.tsx
  src/pages/projects/SpecializedProjectSendRequestListPage.tsx
  src/pages/projects/SpecializedProjectTeamListPage.tsx
  src/pages/projects/SpecializedProjectUserListPage.tsx
  src/pages/projects/TeamCreatePage.tsx
  src/pages/teams/TeamEditPage.tsx
  src/pages/teams/TeamInfoPage.tsx
  src/pages/users/UserInfoPage.tsx
  src/types/commonTypes.ts
Labels: Refactor

#115 Modify : 토큰 만료 시, 로그아웃 및 변수명 수정
  src/components/account/AccountEditCard.tsx
  src/components/account/BasicInformationSection.tsx
  src/components/account/NewPasswordCard.tsx
  src/components/signUp/SignUpForm.tsx
  src/hooks/reduxHooks/useToken.ts
  src/hooks/useMyTeamId.ts
  src/mocks/handlers/authHandlers.ts
  src/services/TokenService.ts
  src/services/UserService.ts
  src/types/signUpTypes.ts
  src/utils/regularExpressionData.ts
Labels: Refactor, Modify

#116 Merge : document 타이틀을 수정하는 커스텀 hook 코드 수정
  src/hooks/useDocumentTitle.ts
Labels: Refactor

#117 Merge : 합류 요청 다이얼 Preloading으로 인한 오류 수정
  src/components/projects/recruitment/UserItem.tsx
  src/components/user/UserInfoSection.tsx
Labels: Fix

#118 Merge : 컴포넌트의 핸들러 네이밍 개편
  src/components/projects/recruitment/Pagenation.tsx
  src/components/projects/recruitment/TeamRecruitmentSection.tsx
  src/components/projects/recruitment/UserItem.tsx
  src/components/projects/recruitment/UserRecruitmentSection.tsx
  src/components/team/TeamCreateForm.tsx
  src/components/team/TeamEditForm.tsx
  src/components/team/TeamInfoSection.tsx
Labels: Refactor

#119 Merge : 서비스 버전 1.2.8 업데이트
  README.md
  package.json
  src/components/account/AccountEditCard.tsx
  src/components/account/BasicInformationSection.tsx
  src/components/account/NewPasswordCard.tsx
  src/components/projects/recruitment/Pagenation.tsx
  src/components/projects/recruitment/TeamRecruitmentSection.tsx
  src/components/projects/recruitment/UserItem.tsx
  src/components/projects/recruitment/UserRecruitmentSection.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/team/TeamCreateForm.tsx
  src/components/team/TeamEditForm.tsx
  src/components/team/TeamInfoSection.tsx
  src/components/user/UserInfoSection.tsx
  src/hooks/reduxHooks/useToken.ts
  src/hooks/useDocumentTitle.ts
  src/hooks/useMyTeamId.ts
  src/mocks/handlers/authHandlers.ts
  src/services/TokenService.ts
  src/services/UserService.ts
  src/types/signUpTypes.ts
  src/utils/regularExpressionData.ts
Labels: Fix, Refactor

#122 Merge : 핸들러 네이밍 수정
  src/components/common/ErrorSection.tsx
  src/components/common/Header.tsx
  src/components/user/UserInfoSection.tsx
  src/components/user/UserLabel.tsx
Labels: Refactor

#123 Merge : 서비스 버전 1.2.9 업데이트
  README.md
  package.json
  src/components/common/ErrorSection.tsx
  src/components/common/Header.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/user/UserInfoSection.tsx
  src/components/user/UserLabel.tsx
  src/mocks/handlers/authHandlers.ts
  src/types/signUpTypes.ts
Labels: Fix
